// Package postgres implements the auth repositories (auth.UserRepository,
// auth.SessionRepository) over PostgreSQL.
//
// It is an adapter: it depends on the auth core (for the ports and sentinel errors)
// and on database/sql, never the reverse — the core imports no SQL (SPEC-003 BR-306,
// SPEC-002 BR-202). All SQL is parameterized; uuid columns are cast to/from text so
// they map cleanly to Go strings (IDs are strings, generated by the database).
package postgres

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgconn"

	"github.com/biel-ferreira/yield-forge/internal/auth"
)

// PostgreSQL SQLSTATE codes we map to domain errors.
const (
	uniqueViolation           = "23505" // unique_violation
	invalidTextRepresentation = "22P02" // e.g. a non-UUID string cast to uuid
)

// Compile-time checks that the adapters satisfy the auth ports.
var (
	_ auth.UserRepository    = UserRepository{}
	_ auth.SessionRepository = SessionRepository{}
)

// UserRepository is the Postgres-backed auth.UserRepository.
type UserRepository struct {
	db *sql.DB
}

// NewUserRepository returns a UserRepository over db.
func NewUserRepository(db *sql.DB) UserRepository { return UserRepository{db: db} }

// CreateUser inserts a new user. A duplicate email (unique violation) is mapped to
// auth.ErrEmailTaken (SPEC-003 FR-301).
func (r UserRepository) CreateUser(ctx context.Context, email, passwordHash string) (auth.User, error) {
	const q = `
		INSERT INTO users (email, password_hash)
		VALUES ($1, $2)
		RETURNING id::text, email, password_hash, created_at, updated_at`
	var u auth.User
	err := r.db.QueryRowContext(ctx, q, email, passwordHash).
		Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.UpdatedAt)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolation {
			return auth.User{}, auth.ErrEmailTaken
		}
		return auth.User{}, fmt.Errorf("create user: %w", err)
	}
	return u, nil
}

// GetUserByEmail returns the user with the given normalized email, or auth.ErrUserNotFound.
func (r UserRepository) GetUserByEmail(ctx context.Context, email string) (auth.User, error) {
	const q = `
		SELECT id::text, email, password_hash, created_at, updated_at
		FROM users WHERE email = $1`
	return scanUser(r.db.QueryRowContext(ctx, q, email))
}

// GetUserByID returns the user with the given id, or auth.ErrUserNotFound.
func (r UserRepository) GetUserByID(ctx context.Context, id string) (auth.User, error) {
	const q = `
		SELECT id::text, email, password_hash, created_at, updated_at
		FROM users WHERE id = $1::uuid`
	return scanUser(r.db.QueryRowContext(ctx, q, id))
}

func scanUser(row *sql.Row) (auth.User, error) {
	var u auth.User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return auth.User{}, auth.ErrUserNotFound
	}
	// A malformed id (non-UUID string cast to uuid) can never match a row, so treat it
	// as not-found rather than surfacing a 500 to a future caller passing a bad id.
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == invalidTextRepresentation {
		return auth.User{}, auth.ErrUserNotFound
	}
	if err != nil {
		return auth.User{}, fmt.Errorf("query user: %w", err)
	}
	return u, nil
}

// SessionRepository is the Postgres-backed auth.SessionRepository.
type SessionRepository struct {
	db *sql.DB
}

// NewSessionRepository returns a SessionRepository over db.
func NewSessionRepository(db *sql.DB) SessionRepository { return SessionRepository{db: db} }

// CreateSession stores a new session row.
func (r SessionRepository) CreateSession(ctx context.Context, userID, tokenHash string, expiresAt time.Time) (auth.Session, error) {
	const q = `
		INSERT INTO sessions (user_id, token_hash, expires_at)
		VALUES ($1::uuid, $2, $3)
		RETURNING id::text, user_id::text, token_hash, expires_at, created_at`
	var s auth.Session
	err := r.db.QueryRowContext(ctx, q, userID, tokenHash, expiresAt).
		Scan(&s.ID, &s.UserID, &s.TokenHash, &s.ExpiresAt, &s.CreatedAt)
	if err != nil {
		return auth.Session{}, fmt.Errorf("create session: %w", err)
	}
	return s, nil
}

// GetSessionByTokenHash returns the session for a token hash, or auth.ErrSessionNotFound.
// Expiry is evaluated by the service against the Clock (BR-307), not filtered here.
func (r SessionRepository) GetSessionByTokenHash(ctx context.Context, tokenHash string) (auth.Session, error) {
	const q = `
		SELECT id::text, user_id::text, token_hash, expires_at, created_at
		FROM sessions WHERE token_hash = $1`
	var s auth.Session
	err := r.db.QueryRowContext(ctx, q, tokenHash).
		Scan(&s.ID, &s.UserID, &s.TokenHash, &s.ExpiresAt, &s.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return auth.Session{}, auth.ErrSessionNotFound
	}
	if err != nil {
		return auth.Session{}, fmt.Errorf("query session: %w", err)
	}
	return s, nil
}

// DeleteSession removes the session with the given token hash (logout). Deleting a
// non-existent session is not an error (SPEC-003 FR-303).
func (r SessionRepository) DeleteSession(ctx context.Context, tokenHash string) error {
	const q = `DELETE FROM sessions WHERE token_hash = $1`
	if _, err := r.db.ExecContext(ctx, q, tokenHash); err != nil {
		return fmt.Errorf("delete session: %w", err)
	}
	return nil
}
